
##############
# Look       #
##############



theme = "tokyonight"


[editor]
auto-save = true
auto-completion = true
line-number = "relative"
mouse = true
true-color = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
select = "underline"
normal = "block"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.lsp]
display-inlay-hints = true
display-messages = true


[editor.indent-guides]
rainbow-option = "normal"
render = true

[editor.whitespace]
tab = "| "

[editor.statusline]
left = [
  "mode",
  "spacer",
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "file-modification-indicator"
]
right = [
  "spinner",
  "spacer",
  "workspace-diagnostics",
  "separator",
  "spacer",
  "diagnostics",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type"
]
separator = "╎"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

############
# Keymaps ##
############

[keys.normal]
# gamming keys
C-a = "vsplit"
C-d = "hsplit"
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = "jump_view_down"
C-k = "jump_view_up"
"C-," = "goto_previous_buffer"
"C-." = "goto_next_buffer"
# file picker with yazi
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
"C-p" = ":lsp-workspace-command tinymist.pinMain %sh{realpath %{buffer_name}}"







# Quit Behavior
[keys.normal.space.q]
q = { q = ":wq"}
# File Picker Behavior 
[keys.normal.space.f]
f = "file_picker_in_current_directory"



