theme = "rose_pine"


[editor]
auto-save = true
auto-completion = true
line-number = "relative"
mouse = true
true-color = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
select = "underline"
normal = "block"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true
display-messages = true


[editor.indent-guides]
rainbow-option = "normal"
render = true

[editor.whitespace]
tab = "| "



