
# python because i'm a chud
[[language]]
name = "python"
language-servers = [ "pyright" ]

# toml
[[language]]
name = "toml"
# https://github.com/tamasfe/taplo/issues/580#issuecomment-2004174721
roots = ["."]
language-servers = ["taplo"]

# VIVA O BRASIL POXA (Lua)
[[language]]
name = "lua"
language-servers = ["lua-language-server"]

# TypeScript and JavaScript
[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

# Rust
[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

# GoLang
[[language]]
name = "go"
language-servers = ["gopls"]

# C
[[language]]
name = "c"
language-servers = ["clangd"]

# C++
[[langauge]]
name = "cpp"
language-servers = ["clangd"]

# Typst
[[language]]
name = "typst"
language-servers = ["tinymist"]

# markdown
[[language]]
name = "markdown"
language-servers = ["markdown-oxide"]
